version: '3.8'

services:
  app:
    build: .
    container_name: your_project_container
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: uv run --with jupyter jupyter lab --ip=0.0.0.0 --no-browser --allow-root